module.exports = Object.freeze({
    // REQUEST_HANDLER: 'REQUEST_HANDLER',
    // ADS_HANDLER: 'ADS_HANDLER',
    // PACKAGE_HANDLER: 'PACKAGE_HANDLER',
    // ACCESS_HANDLER:'ACCESS_HANDLER',
    // VISA_HANDLER:'VISA_HANDLER',
    ADS_HANDLER: "ADS_HANDLER",
    PACKAGE_HANDLER: "PACKAGE_HANDLER",
    REQUEST_HANDLER: "REQUEST_HANDLER",
    BOOKING_MANAGER: "BOOKING_MANAGER",
    CUSTOMER_SUPPORT: "CUSTOMER_SUPPORT",
    CONTENT_MANAGER: "CONTENT_MANAGER",
    FINANCIAL_SUBADMIN: "FINANCIAL_SUBADMIN",
    USER_MANAGER: "USER_MANAGER",
    MARKETING_PROMOTIONS: "MARKETING_PROMOTIONS",
    ANALYTICS_SUBADMIN: "ANALYTICS_SUBADMIN",
    VISA_PROCESSING: "VISA_PROCESSING",
    SECURITY_COMPLIANCE: "SECURITY_COMPLIANCE",
    LOCALIZATION_TRANSLATION: "LOCALIZATION_TRANSLATION",
     EVENT_HANDLER:"EVENT_HANDLER",
    COUPON_CODE_HANDLER:"COUPON_CODE_HANDLER",
   AGENT_MANAGER:"AGENT_MANAGER"

})