module.exports = Object.freeze({
    PRODUCTOFFERING: 'PRODUCTOFFERING',
    AboutUs: 'AboutUs',
    ABOUTTHESITE: 'ABOUTTHESITE',
    QUICKLINKS:'QUICKLINKS',
    IMPORTANTLINKS:'IMPORTANTLINKS',
    CORPORATETRAVEL:'CORPORATETRAVEL',
    QUESTION:'QUESTION',
    

})