module.exports = Object.freeze({
    FLIGHTS: 'FLIGHTS',
    HOTELS: 'HOTELS',
    HOLIDAYS: 'HOLIDAYS',
    TRAINS: 'TRAINS',
    CABS: 'CABS',
    BANKOFFERS: 'BANKOFFERS',
    BUS:'BUS',
    RECHARGES:'RECHARGES',
    EVENTS:'EVENTS',
    PACKAGES:'PACKAGES',
    FORALL:"FORALL"
})