module.exports = Object.freeze({
    TNC: 'T&C',
    PRIVACYPOLICY: 'PRIVACYPOLICY',
    ABOUTUS: 'ABOUTUS',
    RETURNPOLICY:'RETURNPOLICY',
    BOOKINGPOLICY:'BOOKINGPOLICY',
    CORPORATETRAVEL:'CORPORATETRAVEL',
    QUESTION:'QUESTION',
    OTHER:'OTHER'
})