module.exports = {
     packagePrompts:[
        "Show me luxury packages",
        "Packages under 10000",
        "Adventure packages",
        "Beach holidays above 20000",
        "Budget-friendly packages",
        "Family vacation packages",
        "Romantic getaway packages",
        "Winter holiday packages",
        "Show packages with special discounts",
        "Adventure trips in the Alps",
        "Find me the best travel deals to Paris",
        "Show me packages for London in summer",
        "I'm looking for a beach vacation package to Bali",
        "Search for packages with all-inclusive resorts",
        "Find packages within my budget",
        "Show me packages with [specific dates]",
        "I'm flexible on dates, show me the cheapest packages to Rome",
        "Find me flights and hotels to Tokyo for [dates]",
        "Search for packages that include diving",
        "I'm looking for a package with the Ritz-Carlton",
        "Show me packages with [number of travelers]",
        "Find me packages with [specific airline]",
      
        "Find last-minute deals to Barcelona",
        "Show me honeymoon packages",
        "I'm looking for a solo travel package to Amsterdam",
        "Search for packages with a romantic theme",
        "Find packages with luxury travel style",
        "Show me packages with a private pool", 
        "I'm flexible on destination, show me the best deals for winter",
        "Find packages that include train travel",
        "Search for packages with gourmet restaurants",
        "Find packages with hiking activities included",
        "Show me packages with Spanish spoken",
        "Find packages suitable for families",
        "Search for packages with wheelchair accessibility",
        "Find packages with pet-friendly accommodations",
        "Show me packages with [specific loyalty program]",
        "Find packages that support sustainable tourism",
        "I'm looking for a weekend getaway package",
        "Find packages with [specific visa requirements]",
        "Show me packages with travel insurance options",
        "Can you recommend a unique travel experience for me?",
      
        "Show me the most popular travel packages",
        "What are the trending travel destinations right now?",
        "Find me the most booked packages this month",
        "What are the top-rated packages on your platform?",
        "Show me packages that are currently in high demand",
        "What are some hidden gems and off-the-beaten-path packages?",
      
        // Added more specific destination-based prompts
        "Find me the best travel deals to Paris, France",
        "Show me packages for London, England in summer",
        "I'm looking for a beach vacation package to Bali, Indonesia",
        "Find me flights and hotels to Tokyo, Japan for [dates]",
        "Find last-minute deals to Barcelona, Spain",
        "I'm looking for a solo travel package to Amsterdam, Netherlands",
        "Find packages for a trip to Rome, Italy",
        "Show me deals for flights to Dubai, UAE", 
        "Find packages for a trip to New York City, USA",
        "Show me deals for flights to Los Angeles, CA", 
      ]
}