module.exports = {

	UNAUTHORIZED: "User not authorized .",
	OTP_SEND: 'OTP send successfully 🥰',
	OTP_EXPIRED: 'OTP expired😫',
	OTP_NOT_VERIFY: 'Your account is not verified.',
	INCORRECT_OTP: 'Incorrect OTP 😲',
	BLOCK_BY_ADMIN: 'You have been blocked by admin 😶',
	UNBLOCK_BY_ADMIN: 'You have been unblocked by admin',
	DELETE_BY_ADMIN: 'Your account has been deleted by admin',
	NO_TOKEN: 'Please provide token',
	LOGIN: 'Login successfully 🤗',
	OTP_VERIFY: 'OTP verified successfully 😃',
	USER_ALREADY_EXIST: 'User already exist',
	NUMBER_EXIST:'This number is already Exist with another account.',
	USER_NOT_FOUND: 'User not found',
	USERS_NOT_FOUND: 'Users not found',
	USERS_FOUND: 'Users found successfully.',
	CATEGORY_NOT_FOUND: 'Category not found',
	PROFILE_UPDATED: 'Profile updated successfully',
	USER_EXISTS: 'User Exists',
	MOBILE_EXIST: 'This mobile number already exists',
	EMAIL_EXIST: 'This email already exists',
	USER_DETAILS: 'User details',
	USER_CREATED: 'User created successfully',
	CATEGORY_CREATED: 'Category created successfully',
	USER_UPDATED: 'User updated successfully',
	INCORRECT_LOGIN: 'Incorrect login credential provided',
	RESET_LINK_SEND: 'Reset password link has been sent at your email.',
	PWD_CHANGED: 'Password has been changed successfully',
	PWD_NOT_MATCH: 'Password not matched.',
	UPLOAD_SUCCESS: 'File uploaded successfully',
	UPLOAD_FAILURE: 'File not  upload',
	TRANSACTION_SUCCESS: 'Transaction has been completed',
	DATA_FOUND: 'Data found successfully',
	DATA_NOT_FOUND: 'Data not found 4️⃣0️⃣4️⃣',
	DETAILS_FETCHED: 'Details has been fetched successfully 🆗',
	UPDATE_SUCCESS: 'Successfully updated',
	DELETE_SUCCESS: 'Successfully deleted',
	USER_LOGOUT: 'User logged out successfully',
	PROFILE_GET: 'Fetch profile data Successfully',
	INTERNAL_ERROR: 'Internal Error',
	NOT_FOUND: 'Not Found',
	BANNER_ADDED: "Banner added successfully .",
	BANNER_UPDATED: 'Banner updated successfully',
	BLOCK_USER_EMAIL_BY_ADMIN: "This email is blocked by admin try another one.",
	BLOCK_USER_MOBILE_BY_ADMIN: "This mobile is blocked by admin try another one.",
	BLOCK_USER_BY_ADMIN: 'User has been blocked successfully.',
	UNBLOCK_USER_BY_ADMIN: 'User has been Unblocked successfully.',
	SUBSCRIPTION_LIST: 'List of plans.',
	APPROVED: "Agent approved successfully .",
	REJECTED: "Agent rejected successfully .",
	SUBADMIN_ALREADY_EXIST: "SubAdmin Already Exits.",
	ADMIN_NOT_FOUND: 'Admin not found.',
	SUBADMIN_CREATED: "SubAdmin created successfull.",
	INVALID_MODEL: "Invalid model type.",
	REGISTER_SUCCESS: "Registration successful.",
	PASSWORD_NOT_MATCH: "Password and confirm password are not match.",
	ALREADY_VERIFIED: "Your account is already verified.",
	LOGIN_SUCCESS: "Otp send to your registered number. Please verify OTP. 🥰",
	SOCIAL_LOGIN_SUCCESS:"Social login successful🥰",
	FLIGHT_BOOKED: "FlightBooked Successfully.",
	BOOKING_PENDING: "Your booking is pending confirmation.",
	BOOKING_FAILED: "Booking has failed😫. Please try again.😊",
    INVALID_BOOKING_DETAILS: "Invalid booking details provided.",
	AGENT_NOT_FOUND: "Agent not found.",
	FIELD_REQUIRED: "UserName, and Date of Birth is required.",
	AGENT_NOT_FOUND: "Agent not found",
	BOOKING_NOT_FOUND: "Booking is not available.",
	BUS_BOOKING_CREATED: "Bus booking successfully !",
	BOOKING_SUCCESS: "Booking successfully.",
	VISA_CREATED: "Visa Created successfull.",
	CANCEL_REQUEST_SEND: "Your cancel request was send successfully.",
	CANCEL_REQUEST_SEND_TIME_OUT: "Your cancel request is not allowed.",
	ADS_CREATED: "Advertisement added successfull, waiting for approval.",
	POST_CREATED: 'You are posted created successfully.',
	REMOVE_FROM_LIKE: "You have removed your like from the comment.",
	REMOVE_POST_LIKE:"You have removed your like from the post",
	LIKED: "You have liked the comment.",
	POST_LIKED: "You are like the post.",
	CREATED_SUCCESS:"Data was created successfully.",
	QUERY_SUBMITTED:"Dear user your query submitted to our support team, we will reach you soon.",
	QUERY_RESOLVED:"Query is resolved.",
	BAD_REQUEST:"Bad request.",
	STATIC_CREATED:"Static content created successfully.",
	STATIC_DELETED:"Static content deleted successfully.",
	POST_NOT_FOUND:"Post not found.",
	CHANGE_REQUEST_SUCCESS:"Change request submitted succesfully",
	CHANGE_NOT_ALLOW:"Change request not allow for this ticket.",
	PAYMENT_SUCCESS:"Payment Successfully.",
	PDF_SENT:"PDF sent successfully.",
	SUBADMIN_NOT_EXIST:"SubAmdin not exist",
	SUBADMIN_UPDATED:"SubAdmin status updated successfully",
	PAYMENT_INTIATE:"Payment link generated successfully,Please make payment to book ticket.",
	PAYMENT_FAILURE:"Payment failed due to some reason.",
	EVENT_NOT_FOUND:"Event not found.",
	SLOT_NOT_AVAILABLE:'Slot is not available.',
	TRANSACTION_NOT_FOUND:"Transaction not found.",
	SLOT_BOOKED:"Slot booked successfully.",
	DOCUMENTTYPE_NOT_EXIST:"Document Type not exist.",
	PACKAGE_NOT_EXIST:"Package not exist.",
	COUNTRY_NOT_FOUND:"Country not found.",
	COUPON_EXPIRED:"Coupon has expired.",
	ALREDY_COUPOUN_APPLIED:"User has already used this coupon.",
	COUPON_NOT_FOUND:"Coupon not found.",
	COUPON_APPLIED_SUCCESS:"Coupon applied successfully.",
	POST_DELETED:"Post deleted successfull.",
	TASK_CREATED:"Task created successfull.!",
	BLURRY_IMAGE:"image blur , make sure your are in proper light and click a clear picture.!",
	PEFA_NOT_REGISTER:"This coupon is available for those user , who register for pefa2024 event...!",
	EVENT_ALREADY_BOOKED:"You are already registerd for this event.!",
	SUCCESS:"Notification send successfully....!",
	TOKEN_UPDATE_SUCCESS:"Token updated successfully",
	NOTIFICATION_NOT_AVAILABLE:"No new notifications",
	NOTIFICATION_READ:"Notification Read Successfully",
	NOTIFICATION_INCORRECT:"Incorrect notification Id",
	INVALD_REQUEST:"Invalid payment request..",
	PASSES_SENT:"Passes sent successfully to users.",
	REFUND_INITIATE:"Refund Initiated , your amount reflect on your account within 2-3 working days.",
	INCORRECT_REFERRAL:"Incorect referal code,please provide valid code..!",
	LINK_GENERATED:"Link generated successfully",
	ADDED_ON_TREND:"Post Added on trend",
	REFERRALCODE_NOT_EXIST:"Please give a corrected form of refferal code.",
	REFERRALCODE_APPLIED:"Referral code applied successfully.",
	URL_MANDATORY:"Url mandatory.",
	ALREADY_REQUESTED:"Your cancellation request already in our queue,please wait we update you soon.",
	REWARD_DSTRIBUTED:"Reward sent to agent.",
	ALREADY_REWARD_DSTRIBUTED:"Already reward distributed for revenue.",
	No_REVENUE:"No reward generate for this agent.",
	EMAIL_ALREADY_EXIST: 'This email already exist',
	INVALID_FORMAT: 'Please provide valid input',
	PACKAGE_BOOKING_SUCCESS:"Booking Confirmed. Thank you!",
	PAN_NOT_EMPTY:"PAN Number is required and cannot be empty.",
	RESPONSE_SUBMIT:"Thank you for your response!We will announce the lucky winner soon.",
	ALREADY_RESPOND:"You have already submitted your response. Multiple submissions are not allowed.",
	RATING_SUCCESS:"Thanks for your feedback,your feedback help to improve our self🥰",
	RM_LOGIN_SUCCESS:"You are loged in successfull😊",
	EMAIL_SENT:"Reset password link sent on your mail.",
	QUIZ_GET:"Quiz question get successfully!",
	INCORRECT_ANS:"OOPS! 😣 Incorrect answer,please try again tommorrow!😊",
	WIINER_GOT:"Here is our winner of last day quiz!☺️😊",
	ALREADY_LIKE:"Already like this post.",
	WALLET_HISTORY_GET:"Wallet history get successfully.",
	REDEEM_NOT_ALLOW:"Reedem not allow,SkyCoins must be greater than",
	ALLOWED_BALANCE:"Your current withdrawable balance is",
	BLOG_GET_SUCCESSFULLY:"Blog get successfully.!",
	BLOG_NOT_FOUND:"Blog not found.",
	EMAIL_NOT_EXIST:"No account exist with this mail,please go and register first.",
	JOB_CATEGORY_NOT_FOUND:"job category not found",
	HOTEL_NOT_FOUND:"Hotel not found.",
	DATA_SUBMIT_SUCCESSFULL:"Your data has been submitted successfully.",
	PARTNER_NOT_FOUND:"Partner not found!",
	USER_BOOKING_ALREADY_EXIST:"User has existing bookings.",
	USER_FIRST_BOOKING:"This is the user's first booking.",
	REQUEST_ALREADY_EXIST:"Your partnership request is already in queue.",
	REJECTED_ACCOUNT:"Your account is rejected.",
	LOGIN_SUCCESSFULLY:"Loging successfully!🥰",
	PASSWORD_CHANGED:"Paasword change successfully!",
	INCORRECT_PASS:"Incorrect password!",
	USER_NAME_REQUIRED: "Username should not be empty."
};
