module.exports = {

	UNAUTHORIZED: "User not authorized .",
	OTP_SEND: 'OTP send successfully.',
	OTP_EXPIRED: 'OTP expired',
	OTP_NOT_VERIFY: 'Your account is not verified.',
	INCORRECT_OTP: 'Incorrect OTP',
	BLOCK_BY_ADMIN: 'You have been blocked by admin',
	UNBLOCK_BY_ADMIN: 'You have been unblocked by admin',
	DELETE_BY_ADMIN: 'Your account has been deleted by admin',
	NO_TOKEN: 'Please provide token',
	LOGIN: 'Login successfully',
	OTP_VERIFY: 'OTP verified successfully',
	USER_ALREADY_EXIST: 'User already exist',
	USER_NOT_FOUND: 'User not found',
	USERS_NOT_FOUND: 'Users not found',
	USERS_FOUND: 'Users found successfully.',
	CATEGORY_NOT_FOUND: 'Category not found',
	PROFILE_UPDATED: 'Profile updated successfully',
	USER_EXISTS: 'User Exists',
	MOBILE_EXIST: 'This mobile number already exists',
	EMAIL_EXIST: 'This email already exists',
	USER_DETAILS: 'User details',
	USER_CREATED: 'User created successfully',
	CATEGORY_CREATED: 'Category created successfully',
	USER_UPDATED: 'User updated successfully',
	INCORRECT_LOGIN: 'Incorrect login credential provided',
	RESET_LINK_SEND: 'Reset password link has been sent at your email.',
	PWD_CHANGED: 'Password has been changed successfully',
	PWD_NOT_MATCH: 'Password not matched.',
	UPLOAD_SUCCESS: 'File uploaded successfully',
	UPLOAD_FAILURE: 'File not  upload',
	TRANSACTION_SUCCESS: 'Transaction has been completed',
	DATA_FOUND: 'Data found successfully',
	DATA_NOT_FOUND: 'Data not found',
	DETAILS_FETCHED: 'Details has been fetched successfully',
	UPDATE_SUCCESS: 'Successfully updated',
	DELETE_SUCCESS: 'Successfully deleted',
	USER_LOGOUT: 'User logged out successfully',
	PROFILE_GET: 'Fetch profile data Successfully',
	INTERNAL_ERROR: 'Internal Error',
	NOT_FOUND: 'Not Found',
	BANNER_ADDED: "Banner added successfully .",
	BANNER_UPDATED: 'Banner updated successfully',
	BLOCK_USER_EMAIL_BY_ADMIN: "This email is blocked by admin try another one.",
	BLOCK_USER_MOBILE_BY_ADMIN: "This mobile is blocked by admin try another one.",
	BLOCK_USER_BY_ADMIN: 'User has been blocked successfully.',
	UNBLOCK_USER_BY_ADMIN: 'User has been Unblocked successfully.',
	SUBSCRIPTION_LIST: 'List of plans.',
	APPROVED: "Agent approved successfully .",
	REJECTED: "Agent rejected successfully .",
	SUBADMIN_ALREADY_EXIST: "SubAdmin Already Exits.",
	ADMIN_NOT_FOUND: 'Admin not found.',
	SUBADMIN_CREATED: "SubAdmin created successfull.",
	INVALID_MODEL: "Invalid model type.",
	REGISTER_SUCCESS: "Registration successful.",
	PASSWORD_NOT_MATCH: "Password and confirm password are not match.",
	ALREADY_VERIFIED: "Your account is already verified.",
	LOGIN_SUCCESS: "Otp send to your registered number. Please verify OTP.",
	FLIGHT_BOOKED: "FlightBooked Successfully.",
	AGENT_NOT_FOUND: "Agent not found.",
	FIELD_REQUIRED: "fullName,socialId and Date of Birth is required.",
	AGENT_NOT_FOUND: "Agent not found",
	BOOKING_NOT_FOUND: "Booking is not available.",
	BUS_BOOKING_CREATED: "Bus booking successfully !",
	BOOKING_SUCCESS: "Booking successfully.",
	VISA_CREATED: "Visa Created successfull.",
	CANCEL_REQUEST_SEND: "Your cancel request was send successfully.",
	CANCEL_REQUEST_SEND_TIME_OUT: "Your cancel request is not allowed.",
	ADS_CREATED: "Advertisement added successfull, waiting for approval.",
	POST_CREATED: 'You are posted created successfully.',
	REMOVE_FROM_LIKE: "You have removed your like from the comment.",
	REMOVE_POST_LIKE:"You have removed your like from the post",
	LIKED: "You have liked the comment.",
	POST_LIKED: "You are like the post.",
	CREATED_SUCCESS:"Data was created successfully.",
	QUERY_SUBMITTED:"Dear user your query submitted to our support team, we will reach you soon.",
	QUERY_RESOLVED:"Query is resolved.",
	BAD_REQUEST:"Bad request.",
	STATIC_CREATED:"Static content created successfully.",
	STATIC_DELETED:"Static content deleted successfully.",
	POST_NOT_FOUND:"Post not found.",
	CHANGE_REQUEST_SUCCESS:"Change request submitted succesfully",
	CHANGE_NOT_ALLOW:"Change request not allow for this ticket.",
	PAYMENT_SUCCESS:"Payment Successfully.",
	PDF_SENT:"PDF sent successfully.",
	SUBADMIN_NOT_EXIST:"SubAmdin not exist",
	SUBADMIN_UPDATED:"SubAdmin status updated successfully",
	PAYMENT_INTIATE:"Payment link generated successfully,Please make payment to book ticket.",
	PAYMENT_FAILURE:"Payment failed due to some reason.",
	EVENT_NOT_FOUND:"Event not found.",
	SLOT_NOT_AVAILABLE:'Slot is not available.',
	TRANSACTION_NOT_FOUND:"Transaction not found.",
	SLOT_BOOKED:"Slot booked successfully.",
	DOCUMENTTYPE_NOT_EXIST:"Document Type not exist.",
	PACKAGE_NOT_EXIST:"Package not exist.",
	COUNTRY_NOT_FOUND:"Country not found.",
	COUPON_EXPIRED:"Coupon has expired.",
	ALREDY_COUPOUN_APPLIED:"User has already used this coupon.",
	COUPON_NOT_FOUND:"Coupon not found.",
	COUPON_APPLIED_SUCCESS:"Coupon applied successfully.",
	POST_DELETED:"Post deleted successfull.",
	TASK_CREATED:"Task created successfull.!",
	BLURRY_IMAGE:"image blur , make sure your are in proper light and click a clear picture.!",
	PEFA_NOT_REGISTER:"This coupon is available for those user , who register for pefa2024 event...!"
};
